version: '3.1'

services:
  web:
    image: wordpress:${WORDPRESS_IMAGE_VERSION}
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 1g
    restart: always
    ports:
      - 8002:80
    environment:
      WORDPRESS_DB_HOST: sql
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - web:/var/www/html
    networks: 
        - wp-vnet
  sql:
    image: ${MYSQL_IMAGE}
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 1g
    restart: always
    ports: 
        - 3306:3306
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - sql:/var/lib/mysql
    networks: 
      wp-vnet:
volumes:
  web:
  sql:
networks: 
  wp-vnet: