version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: 8n923487n92m
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
    networks: 
        - wordpress-vnet

  db:
    image: mysql:5.7
    restart: always
    ports: 
        - 3306:3306
    environment:
      MYSQL_DATABASE: 8n923487n92m
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: 8n923487n92m
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks: 
        wordpress-vnet:

volumes:
  wordpress:
  db:
networks: 
    wordpress-vnet: