version: '3.1'

services:
  web:
    image: wordpress:${WORDPRESS_IMAGE_VERSION}
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: sql
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - web:/var/www/html
    networks: 
        - wordpress-vnet

  sql:
    image: mysql:${MYSQL_IMAGE_VERSION}
    restart: always
    ports: 
        - 3306:3306
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - sql:/var/lib/mysql
    networks: 
        wordpress-vnet:

volumes:
  web:
  sql:
networks: 
    wordpress-vnet: