version: '3'
services:
   sql:
    image: ${SQL_IMAGE}
    deploy:
      resources:
        limits:
          cpus: 2
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: ${ACCEPT_EULA}
      MSSQL_MEMORY_LIMIT_MB: 2048
    ports:
      - 1401:1433
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "${SA_PASSWORD}", "-Q", "select 1"]
      interval: 10s
      retries: 10
    volumes:
      - sqlvolume:/var/opt/mssql
    networks: 
      - octopus-vnet
   web:
    image: octopusdeploy/octopusdeploy:${OCTOPUS_SERVER_TAG}
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 1g
    privileged: ${PRIVILEGED}
    user: ${USER}
    environment:
      ACCEPT_EULA: ${ACCEPT_OCTOPUS_EULA}
      OCTOPUS_SERVER_NODE_NAME: ${OCTOPUS_SERVER_NODE_NAME}
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      OCTOPUS_SERVER_BASE64_LICENSE: ${OCTOPUS_SERVER_BASE64_LICENSE}
      MASTER_KEY: ${MASTER_KEY}
      ADMIN_API_KEY: ${ADMIN_API_KEY}
      DISABLE_DIND: ${DISABLE_DIND}
    ports:
      - 8001:8080
      - 11111:10943
    depends_on:
      sql:
        condition: service_healthy
        condition: service_started
    dns: 
      - 192.168.1.71
    volumes:
      - repository:/repository
      - artifacts:/artifacts
      - taskLogs:/taskLogs
      - cache:/cache
      - import:/import
      - octopus:/Octopus
    networks: 
      octopus-vnet:
volumes:
  repository:
  artifacts:
  taskLogs:
  cache:
  import:
  octopus:
  sqlvolume:
networks: 
  octopus-vnet: